<a href="https://colab.research.google.com/github/rasulovasevara00-web/week_3lab/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(100)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(100)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [2]:
# TODO: Create a vector tensor
vector = torch.tensor([1,2,3,4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [3]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1,2,3],
                      [4,5,6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [4]:
# TODO: Create a 3D tensor
tensor_3d = torch.arange(1,9).reshape(2,2,2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [5]:
# TODO: Create random tensor
random_tensor = torch.zeros(size=(4,4))

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [6]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(size=(3,224,224))

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [7]:
# TODO: Create zeros tensor
zeros = torch.zeros(size=(5,5))
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [8]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones(size=(3,3))
print(ones_like)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [9]:
# TODO: Create range tensor
range_tensor = torch.arange(start=0,end=20,step=2)
range_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [10]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0,2.0,3.0],
                              dtype=torch.float16)

# TODO: int64 tensor
int64_tensor = torch.tensor([1.0,2.0,3.0],
                            dtype=torch.int64)
float16_tensor
int64_tensor

tensor([1, 2, 3])

### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [11]:
# TODO: Change dtype
float32_tensor = float16_tensor.to(torch.float32)
print(float32_tensor)

tensor([1., 2., 3.])


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [12]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2,3,4)
print(f"The size of tensor:  {info_tensor.shape}")
print(f"The data type  of tensor: {info_tensor.dtype}")
print(f"The info_tensor is stored on: {info_tensor.device}")

The size of tensor:  torch.Size([2, 3, 4])
The data type  of tensor: torch.float32
The info_tensor is stored on: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [15]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
add = tensor + 5

# TODO: Subtract 10
sub = tensor - 10

# TODO: Multiply by 2
mul = tensor * 2

# TODO: Divide by 10
div = tensor / 10
print(add,sub,mul,div)

tensor([15, 25, 35]) tensor([ 0, 10, 20]) tensor([20, 40, 60]) tensor([1., 2., 3.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [14]:
# TODO: Create A and B
A = torch.rand(2,3)
B = torch.rand(3,2)

# TODO: Matrix mul using torch.mm
result_mm = torch.matmul(A,B)

# TODO: Matrix mul using @
result_at = A@B
print(result_mm,result_at)

tensor([[1.1135, 0.4597],
        [1.3008, 0.5378]]) tensor([[1.1135, 0.4597],
        [1.3008, 0.5378]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [13]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
print(f"Min of tensor: {agg_tensor.min()}")

# TODO: Max
print(f"Max of tensor: {agg_tensor.max()}")

# TODO: Mean (note: may need to cast to float)
print(f"Mean of tensor: {agg_tensor.type(torch.float32).mean()}")
# TODO: Sum
print(f"Sum of tensor elements: {agg_tensor.sum()}")

Min of tensor: 0
Max of tensor: 100
Mean of tensor: 50.0
Sum of tensor elements: 5050


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [16]:
# TODO: Argmax
print(f"Index which has maximum value: {agg_tensor.argmax()}")
# TODO: Argmin
print(f"Index which has minimum value: {agg_tensor.argmin()}")

Index which has maximum value: 100
Index which has minimum value: 0


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [17]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor.reshape(2,5)
print(reshaped)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [19]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
ver_stack = torch.vstack((tensor1,tensor2))

# TODO: Stack horizontally (dim=1)
hor_stack = torch.hstack((tensor1,tensor2))

### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [20]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = squeeze_tensor.squeeze()

# TODO: Unsqueeze on dim=0
unsqueezed = squeeze_tensor.unsqueeze(dim=0)

### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [21]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = torch.permute(image_tensor, (1,2,0))
print(permuted)

tensor([[[0.9844, 0.4526, 0.2795],
         [0.9886, 0.2571, 0.5263],
         [0.4921, 0.6398, 0.7512],
         ...,
         [0.6536, 0.7589, 0.0751],
         [0.5163, 0.0471, 0.7218],
         [0.6594, 0.7277, 0.8988]],

        [[0.1334, 0.3481, 0.6626],
         [0.7183, 0.1704, 0.4887],
         [0.6049, 0.6321, 0.4430],
         ...,
         [0.1692, 0.2424, 0.9288],
         [0.8073, 0.3410, 0.7824],
         [0.0740, 0.2763, 0.9671]],

        [[0.4161, 0.8787, 0.2221],
         [0.5343, 0.5941, 0.4574],
         [0.1421, 0.4309, 0.7118],
         ...,
         [0.1048, 0.3785, 0.1679],
         [0.2096, 0.5079, 0.0351],
         [0.8715, 0.7362, 0.5683]],

        ...,

        [[0.8239, 0.0835, 0.4945],
         [0.6398, 0.9913, 0.3862],
         [0.9243, 0.8371, 0.8094],
         ...,
         [0.2792, 0.5534, 0.7176],
         [0.8953, 0.7660, 0.8073],
         [0.5253, 0.9140, 0.4615]],

        [[0.9475, 0.3167, 0.8799],
         [0.8738, 0.7474, 0.6539],
         [0.

## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [22]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
print(image_tensor[1][1])

# TODO: Get second row [4,5,6]
print(image_tensor[1])

tensor([0.3481, 0.1704, 0.6321, 0.8257, 0.1875, 0.2846, 0.2237, 0.1733, 0.0572,
        0.6264, 0.7127, 0.9451, 0.1267, 0.9983, 0.8577, 0.7722, 0.9878, 0.1557,
        0.6055, 0.4695, 0.9623, 0.8171, 0.9004, 0.5337, 0.9348, 0.8281, 0.3004,
        0.6597, 0.4178, 0.9780, 0.3006, 0.8926, 0.5410, 0.6687, 0.4018, 0.8970,
        0.3592, 0.4713, 0.6975, 0.9927, 0.8266, 0.1797, 0.1713, 0.6024, 0.0191,
        0.0777, 0.2893, 0.3907, 0.6415, 0.9856, 0.9721, 0.8012, 0.4389, 0.8784,
        0.2849, 0.7175, 0.3979, 0.6716, 0.3797, 0.8047, 0.0884, 0.4475, 0.8006,
        0.0605, 0.7907, 0.7568, 0.8105, 0.1557, 0.0198, 0.0286, 0.6703, 0.4822,
        0.3325, 0.3782, 0.1964, 0.6663, 0.1831, 0.0282, 0.1599, 0.4889, 0.1851,
        0.2238, 0.6528, 0.6328, 0.4614, 0.0442, 0.4625, 0.5988, 0.1807, 0.5361,
        0.9438, 0.1781, 0.7659, 0.0163, 0.1552, 0.2187, 0.9476, 0.2424, 0.3410,
        0.2763])
tensor([[0.4526, 0.2571, 0.6398,  ..., 0.7589, 0.0471, 0.7277],
        [0.3481, 0.1704, 0.6321,  ..., 

## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [23]:
import numpy as np
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)

### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [24]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = tensor.numpy()

## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [25]:
import torch

torch.manual_seed(77)
rand1 = torch.rand(2, 2)

torch.manual_seed(77)
rand2 = torch.rand(2, 2)


print(rand1 == rand2)

tensor([[True, True],
        [True, True]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [26]:
# TODO: Set device
device = device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

Using device: cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [27]:
gpu_tensor = torch.tensor([10, 20, 30])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
gpu_tensor = gpu_tensor.to(device)
cpu_numpy = gpu_tensor.cpu().numpy()

print("Tensor on device:", gpu_tensor)
print("NumPy array on CPU:", cpu_numpy)

Tensor on device: tensor([10, 20, 30])
NumPy array on CPU: [10 20 30]
